name: Check README Syntax
on:
  pull_request:
    branches: [ develop ]
    types: [ opened, reopened ]
jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar lint para el markdown
        run: |
          sudo apt-get update
          sudo apt-get install -y markdownlint

      - name: Lint README.md
        run: markdownlint README.md

